### PR TITLE
Unify sanity checks

### LINKED ISSUE #159: room.set_user_profile() breaks when logging in with bare username
If I log in as just "Coffee", that works just fine, but `room.set_user_profile()` breaks with 404 response because it tries to PUT `*/state/m.room.member/Coffee`. This should be `*/state/m.room.member/@Coffee:matrix.org`.

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #159 
@Matrixcoffee /cc
@non-Jedi /cc

### CODE REVIEW

**Comment by non-Jedi** [comment]
Signoff please and fix following PEP8 issues:

- matrix_client/checks.py:8:1: E302 expected 2 blank lines, found 1
- matrix_client/user.py:3:1: E302 expected 2 blank lines, found 1

**Comment by Androbin** [comment]
Fixed PEP8, rebased and signed off

**Comment by non-Jedi** [comment]
LGTM. Appreciate this. :)

**Comment by Androbin** [comment]
Where else could potentially "dirty" `room_id` and `user_id` values be passed?
Should we add this to deprecated [`client.set_user_id`](https://github.com/Androbin/matrix-python-sdk/blob/master/matrix_client/client.py#L164) or wait for it's removal?

**Comment by non-Jedi** [comment]
Not sure, and I'm ambivalent on that one.

**Comment by Matrixcoffee** [comment]
Great stuff.

Just one remark: Although room IDs should be fitted with a domain part on creation, those are only informational, and room IDs should be treated as opaque strings anywhere else. Since the domain part isn't actually used by anything, the utility of checking for it seems marginal at best, and it may cause trouble down the road.

**Comment by Androbin** [comment]
How about an additional defaulted flag?
`def check_room_id(room_id, require_domain=False):`
We would then pass `require_domain=True` on creation.

**Comment by non-Jedi** [comment]
While room IDs may one day be truly opaque and should in general be treated as such by clients, [the spec currently says that room ids must have a domain part](https://matrix.org/docs/spec/appendices.html#room-ids-and-event-ids), so I think leaving the check as-is is reasonable until the spec is changed.

**Pull request merged**
