### PR TITLE
Warn applications about deprecated methods

### LINKED ISSUE #146: Warn applications about deprecated methods
Several methods in `MatrixClient` are described as deprecated in their docstrings. We should also be calling `warnings.warn` from within the methods.

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #146
@non-Jedi /cc
Signed-off-by: Robin Richtsfeld <robin.richtsfeld@gmail.com>

### CODE REVIEW

**Comment by Matrixcoffee** [comment]
I have some comments though.
* Typo in https://github.com/Androbin/matrix-python-sdk/blob/99002f315425435fa84660ae391117dbdf805c2d/matrix_client/api.py#L197
* [This warning](https://github.com/Androbin/matrix-python-sdk/blob/99002f315425435fa84660ae391117dbdf805c2d/matrix_client/client.py#L400) in listen_for_events recommends to use `_sync`. However, starting your method name with an underscore is a common convention in Python to signal that this method is not part of the official API.
Other than that, looking good.

**Comment by Matrixcoffee** [comment]
Oh, and to head off the question you will undoubtedly have: I would just drop the recommendation. The API is still beta and this is one of those places where it shines through.

**Comment by Matrixcoffee** [comment]
Oh, and to head off the question you will undoubtedly have: I would just drop the recommendation, but maybe @non-jedi has something to say about that as well. The API is still beta and this is one of those places where it shines through.

**Comment by non-Jedi** [comment]
Off the top of my head, it seems like we should just expose `_sync` as `sync`. Doesn't seem like something we necessarily need to put a ton of machinery in front of.

**Comment by Matrixcoffee** [comment]
@Half-Shot: You have written a lot of this stuff and seem to have had a plan for deprecating initialsync. What do you think?

**Pull request closed without merging**
