### PR TITLE
Send token in Authorization header

### PR DESCRIPTION
**Pull request by slipeer**
By default send user token in Authorization header istead of query string. Same behavior as in latest Riot.IM versions. As result more readeble query logs.
Tests for API _send method.

### CODE REVIEW

**Comment by Half-Shot** [comment]
Is there a reason to keep the old way around, the header seems like a net gain to me?

**Comment by slipeer** [comment]
@Half-Shot I do not know of such reasons. just always try to leave compatibility. I can remove it if it's critical.

**Comment by non-Jedi** [comment]
This is great! Thanks for all the new tests. This is good to merge once signed off on per CONTRIBUTING.rst.

**Comment by slipeer** [comment]
Signed-off-by: Pavel Kardash <slipeer@gmail.com>

**Comment by non-Jedi** [comment]
Cherry-picked into master. Thanks!

**Pull request closed without merging**
