### PR TITLE
Fix client listeners

### PR DESCRIPTION
**Pull request by anewusername**
Signed-off-by: Jan Petykiewicz <anewusername@gmail.com>

### CODE REVIEW

**Comment by Half-Shot** [comment]
Oops :o

**Comment by Half-Shot** [comment]
ok to test

**Comment by Half-Shot** [comment]
Hang on a second. That code shouldn't be in there at all...quite embarrassing. Not sure how the client listener code ended up inside Room.py.

**Comment by anewusername** [comment]
Yeah, looks like it gets called twice -- switched out the commit for one that removes the client listener code from room.py

**Comment by Half-Shot** [comment]
Okay LGTM

**Pull request merged**
