### PR TITLE
Change from LBYL to EAFP style.

### PR DESCRIPTION
**Pull request by yuvallanger**
http://docs.quantifiedcode.com/python-anti-patterns/readability/asking_for_permission_instead_of_forgiveness_when_working_with_files.html
https://docs.python.org/3/glossary.html#term-eafp
https://docs.python.org/3/glossary.html#term-lbyl

### CODE REVIEW

**Comment by NotAFile** [comment]
IMO, `list.get()` is superior to either method.

**Comment by yuvallanger** [comment]
There is no `get` method to the `list` type.

Maybe you'd like the following:

```
argv_dict = dict(enumerate(argv))

host = argv_dict.get(1)
username = argv_dict.get(2)
password = argv_dict.get(3)

if host is None:
    host = get_input("Host (ex: http://localhost:8008 ): ")

if username is None:
    username = get_input("Username: ")

if password is None:
    password = getpass() # Hide user input
```

**Comment by non-Jedi** [comment]
This looks like *marginal* readability improvement to me. Sign-off per contributing.rst, and I can merge.

**Comment by non-Jedi** [comment]
LGTM. Thanks!

**Pull request merged**
