### PR TITLE
Added API and methods for setting room name and topic

### PR DESCRIPTION
**Pull request by anewusername**
I followed the general format of get_room_topic and update_room_topic.

### CODE REVIEW

**Comment by Half-Shot** [comment]
ok to test

**Comment by SShrike** [comment]
test to ok

**Comment by Half-Shot** [comment]
#58 is moving room and user to their own files (which should really have been in it's own PR but what's done is done) so I'm going to wait for that to be merged first. You'll need to update your code to match and then this can be merged :)

**Comment by Half-Shot** [comment]
Said PR has been merged, so please update when you are ready.

**Comment by Half-Shot** [comment]
LGTM

**Comment by anewusername** [comment]
Signed-off-by: Jan Petykiewicz <anewusername@gmail.com>

**Pull request merged**
