### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by dovf**
The main real change here is to require the user_id when constructing from an existing token, as we want to ensure that this information is available regardless of how the instance was constructed.

In addition, some README changes which also mostly relate to the login process -- I'm not sure all the changes are correct, please check that they are...!

### CODE REVIEW

**Comment by erikjohnston** [comment]
@matrixbot test this please

**Comment by erikjohnston** [comment]
http://matrix.org/jenkins/job/PythonSDK-PR/64/violations/file/matrix_client/client.py/

**Comment by dovf** [comment]
Fixed the pep8 issue.

**Comment by Half-Shot** [comment]
LGTM

**Pull request merged**
