### PR TITLE
Add ability to send html text to matrix...

### PR DESCRIPTION
**Pull request by szimszon**
...based on room.py

### CODE REVIEW

**Comment by non-Jedi** [comment]
Hi @szimszon. What's the purpose of this patch? The behavior added is already available (as you noted) in room.py.

**Comment by szimszon** [comment]
The https://github.com/opsdroid/connector-matrix/blob/master/matrix_async.py uses the api only:
--- cut ---
from matrix_client.api import MatrixHttpApi
--- cut ---

But just with api I can't send html messages only text... And I would like to extend (if possible) opsdroid's matrix connector so that I would be able to send formatted html text... I have a skill to run just a shell script and I would like to have the output with a fixed width text.

**Comment by non-Jedi** [comment]
Hey @szimszon. This is high-level behavior that belongs only in the client.py/room.py level of abstraction rather than at the api.py level. This code from room.py is of course Apache license, and you're welcome to copy-paste it into your own projects subject to that license. Sorry. Let me know if it's not clear why I can't merge this, and we can talk about it in [#matrix-python-sdk:matrix.org](https://matrix.to/#/%23matrix-python-sdk:matrix.org).

**Comment by szimszon** [comment]
Hi,

I see. You are right. I will use the api.send_message_event(...) for that.

**Pull request closed without merging**
