### PR TITLE
matrix_client: Add send location requests

### PR DESCRIPTION
**Pull request by GalPressman**
Introduce send_location() to api and client.
Implemented according to:
http://matrix.org/docs/spec/client_server/r0.2.0.html#m-image

Signed-off-by: Gal Pressman <galpressman@gmail.com>

### CODE REVIEW

**Comment by Half-Shot** [comment]
Hmm. Interesting one. Not sure I've seen this used in the wild yet and I don't know how valid this still is in the grand scheme of things. I'm happy to merge, just not sure how it would look on any client right now :laughing:

**Comment by Half-Shot** [comment]
Ok to test

**Comment by GalPressman** [comment]
I though it's a matter of time until clients like riot will support locations.
If this is not the case, I guess there is no point in adding dead code to this project.

**Comment by Half-Shot** [comment]
I did indeed write a PR for riot that supports locations, though unfortunately we never got around to merging it due to a few bugs around thumbnailing. I'd recommend you sanitize the geo uri before sending just to keep things in order.

Other than that, LGTM.

**Comment by GalPressman** [comment]
What do you mean by sanitize? check for a regex match?

**Comment by Half-Shot** [comment]
Yep, like in https://tools.ietf.org/rfc/rfc5870

**Comment by GalPressman** [comment]
> The syntax of the ’geo’ URI scheme is specified below in Augmented
>  Backus-Naur Form (ABNF) [RFC5234]:
>  geo-URI = geo-scheme ":" geo-path
>  geo-scheme = "geo"
>  geo-path = coordinates p
>  coordinates = coord-a "," coord-b [ "," coord-c ]
>  coord-a = num
>  coord-b = num
>  coord-c = num
>  p = [ crsp ] [ uncp ] *parameter
>  crsp = ";crs=" crslabel
>  crslabel = "wgs84" / labeltext
>  uncp = ";u=" uval
>  uval = pnum
>  parameter = ";" pname [ "=" pvalue ]
>  pname = labeltext
...

I don't think I can find a regex to match all the cases mentioned here 😆.

**Comment by Half-Shot** [comment]
Oh wow, I didn't realise it was so...verbose. I won't hold you to validating it in that case.

**Comment by Half-Shot** [comment]
LGTM. Merging

**Pull request merged**
