### PR TITLE
Add Tag Endpoints 

### PR DESCRIPTION
**Pull request by pik**
This PR adds tag endpoints (`GET`, `PUT`, `DELETE`) as per the spec (http://matrix.org/docs/spec/client_server/r0.2.0.html#client-config) to the sdk. 

Also I extracted Room and User classes to their own files to make code a little better organized / easier to navigate (I'll extract that to a separate PR if it's preferred though).

### CODE REVIEW

**Comment by Half-Shot** [comment]
Oooh, thanks :)

I would have preferred it if you had extracted the classes in a separate PR, but I was going to do it anyhow and it's more effort to start dissecting your commits.

**Comment by Half-Shot** [comment]
Okay to test

**Comment by Half-Shot** [comment]
ok to test

**Comment by Half-Shot** [comment]
@pik If you could fix the errors, then I'd be happy with the changes

**Comment by pik** [comment]
@Half-Shot Sorry about neglecting this -- updated.

**Comment by Half-Shot** [comment]
@pik I forgot to ask you to sign this off. Could you read through https://github.com/matrix-org/matrix-python-sdk/blob/master/CONTRIBUTING.rst#sign-off and do so please :)

**Pull request merged**
