### PR TITLE
Dispatch room events to client listeners

### PR DESCRIPTION
**Pull request by gergelypolonkai**
This is an attempt to solve #43 and make both parties happy.

Signed-off-by: Gergely Polonkai <gergely@polonkai.eu>

### CODE REVIEW

**Comment by gufogio** [comment]
Many thanks @gergelypolonkai!

I think we should add a `room_id` argument to the event, I don't think that's already there :smiley:

**Comment by gergelypolonkai** [comment]
As far as I observed, the listener gets a `Room` object, which has a `.room_id` property. I don’t think that is actually necessary.

**Comment by gufogio** [comment]
Oh well you're right, sorry :)

**Comment by Half-Shot** [comment]
LGTM

**Pull request merged**
