### PR TITLE
Replace calls of deprecated login methods in examples

### PR DESCRIPTION
**Pull request by sblondon**
The examples in `samples/` directory used `MatrixClient.login_with_password()` and
`MatrixClient.login_with_password_no_sync()`. These calls are replaced
by newer `MatrixClient.login()` method.

### CODE REVIEW

**Comment by Half-Shot** [comment]
Hiya, CI appears to be broken and will be fixed by #307 so I'll wait for that before merging. Can you also sign off as stated in https://github.com/matrix-org/matrix-python-sdk/blob/master/CONTRIBUTING.rst :)

**Comment by sblondon** [comment]
Thanks for the quick review! :)

I added a 'sign-off-by' line in https://github.com/matrix-org/matrix-python-sdk/pull/306/commits/2dda341144b6e0f9fa0fcdb4190b1aa2f0b5d8d0

**Comment by claudep** [comment]
Looks like this could be pushed now the CI is green again!

**Comment by non-Jedi** [comment]
He's right. @sblondon, could you please rebase on master so CI passes?

**Comment by sblondon** [comment]
After the rebase, the CI is green. However, as the new commits are visible, I guess I failed to do a clean rebase.

I done:
```
git remote add upstream https://github.com/matrix-org/matrix-python-sdk.git
git fetch upstream
git checkout master
git rebase upstream/master
git checkout replace_login_with_password_method_call
git rebase upstream/master
git push
```

If you prefer, I can close this PR and create a new one.

**Comment by non-Jedi** [comment]
Don't worry about it. I'll just cherry-pick your commit. Thanks for updating these.

**Pull request closed without merging**
