### PR TITLE
matrix_client: Add logout functionality

### PR DESCRIPTION
**Pull request by GalPressman**
```
Ideally, each login usage should be cleaned up eventually
using logout to free unnecessary resources and invalidate the token.

Issue: #68
Signed-off-by: Gal Pressman <galpressman@gmail.com>
```

Please let me know if you think we should also set our inner state to reflect the logout operation.

### CODE REVIEW

**Comment by Half-Shot** [comment]
ok to test

**Comment by Half-Shot** [comment]
Tiny tiny request: Could you store the thread object from ``start_listener_thread`` and make sure it's stopped running before you perform the logout? Just in case users don't stop it themselves.

**Comment by GalPressman** [comment]
AFAIK there is no _nice_ way to stop a `threading` thread, unless we want to involve some synchronization between the threads - or just use `subprocess` module instead.
Feel free to enlighten me though :)

**Comment by Half-Shot** [comment]
The way I was thinking is
```
def listen_forever(...):
   while(self.should_listen):
      ...


def start_listener_thread(...):
   ...
   self.should_listen = true;
   ...

def stop_listener_thread(...):
   self.should_listen = false
   self.sync_thread.join()


def logout(self):
   self.stop_listener_thread()
```

Now there are a few issues:
* The requests lib is blocking, so we'd need to start working out ways to cancel requests which probably means changing libraries. Not going to look into that right now for the sake of this PR.
* Do we want to block logout  with .join()?

There are certainly uses for wanting to block logout(). If the user wishes to change their account for instance, or just wishes to change their token. There are also issues in that you are going to be waiting for a sync to complete before the logout will finish. 

I'll leave the option up to you, if not then I'll probably leave this as an exercise to myself :wink:

**Comment by GalPressman** [comment]
In my opinion blocking until we are done with `sync` is correct, when `logout` is done I want to be certain that all leftovers are cleaned up for me.
I will implement according to your suggestion.

**Comment by Half-Shot** [comment]
Awesome, let me know if you run into any problems :)

**Comment by GalPressman** [comment]
Seems to fail because of unrelated errors:
`samples/SimpleChatClient.py:74:1: E305 expected 2 blank lines after class or function definition`

While we're at it, why doesn't Jenkins show the errors? it only shows the commands so I can run them locally, which is _ok_, but kinda annoying.

**Comment by Half-Shot** [comment]
Yes, I appear to have upset it :P. Still working on that one.

**Comment by Half-Shot** [comment]
This can be merged, the issue is something I'll have to find out from someone internal.

**Pull request merged**
